"""
instrlib.instrument — @Instrument class decorator + Logger
===========================================================
This module provides the two central components of the real InstrLib pattern:

    Logger      — ties PEP, Schema and PDP together; provides log() / log_only()
    Instrument  — class decorator that transparently instruments application classes

THE KEY IDEA (@Instrument)
===========================
In our v1 proxy, enforcement was explicit in application code:

    final_response = pep.enforce(mappings.ask_action, event_id, llm_response)

The application module had to know about pep, mappings, event_ids.

In this v2, the application class is completely unaware of enforcement:

    @Instrument(logger)
    class LLMProxy:
        def chat(self, event_id: int, llm_response: str) -> str:
            return llm_response    ← just the baseline application logic

The @Instrument decorator intercepts every call to LLMProxy.chat(), runs the
η_i mapping to produce events, calls the Logger (which calls EnfGuard), then
routes the verdict to the registered η_e handlers — all transparently.

The application module never imports handlers, mappings, pep, or pdp.

HOW @Instrument WORKS
======================
1.  @Instrument(logger) receives the class at decoration time.
2.  It iterates over the class's methods with dir(cls).
3.  For each method whose (ClassName, methodName) tuple is in pep.mapping,
    it replaces the method with a generated wrapper using setattr().
4.  The wrapper does:
        a. events = mapping_fn(*args, **kwargs)    ← η_i
        b. verdict = logger.log(events)            ← PDP
        c. original_result = original(inst, ...)   ← baseline application logic
        d. route verdict to handler                ← η_e
        e. return enforced result

This is faithful to the real library's instrument.py with one simplification:
the real library uses a three-thread async architecture. Here log() is
synchronous (batch subprocess), which is correct for our sequential model.

REAL LIBRARY REFERENCE
=======================
    miniTwitter_case_study/instrlib/instrument.py
    (in the instrlib-main folder on the Desktop)
"""

from typing import Any, Callable, Dict, List, Optional, Set, Tuple, Type

from instrlib.event import Event
from instrlib.pep import PEP
from instrlib.pdp import EnfGuardPDP
from instrlib.schema import Schema


# ── Logger ────────────────────────────────────────────────────────────────────

class Logger:
    """
    Central coordinator: holds PEP + Schema + PDP, provides log() / log_only().

    In the real library, Logger also owns the three background threads (timer,
    writer, reader) and a result cache. We keep the interface identical but
    implement log() synchronously.

    Attributes
    ----------
    pep     : Policy Enforcement Point (mappings + handlers)
    schema  : event type validator
    pdp     : EnfGuardPDP (the actual enforcer)
    """

    def __init__(self, pep: PEP, schema: Schema, pdp: EnfGuardPDP) -> None:
        self.pep    = pep
        self.schema = schema
        self.pdp    = pdp

    def reset(self) -> None:
        """Clear PDP log. Call at server startup."""
        self.pdp.reset()

    # ── Main enforcement path ─────────────────────────────────────────────────

    def log(
        self,
        events: List[Event],
    ) -> Tuple[bool, bool, Dict[str, List[tuple]], Dict[str, List[tuple]]]:
        """
        Validate events, send to EnfGuard, return parsed verdict.

        This is the method called by the @Instrument wrapper for every
        instrumented method invocation.

        Parameters
        ----------
        events   : events generated by η_i for this method call

        Returns
        -------
        (cau_flag, sup_flag, cau_enc, sup_enc)
            cau_flag : True if EnfGuard issued any Cause command
            sup_flag : True if EnfGuard issued any Suppress command
            cau_enc  : {"EventName": [(arg0, arg1, ...), ...], ...}
            sup_enc  : {"EventName": [(arg0, arg1, ...), ...], ...}
        """
        # Step 1: validate against schema
        for event in events:
            self.schema.validate(event)

        # Step 2: derive timestep from first event's first arg (= request ID)
        timestep = events[0].args[0] if events and events[0].args else 0

        # Step 3: run EnfGuard via PDP
        raw = self.pdp.process_events(events, timestep)

        # Step 4: parse into typed verdict dicts
        cau_enc: Dict[str, List[tuple]] = {}
        sup_enc: Dict[str, List[tuple]] = {}

        for item in raw.get("caused", []):
            name = item["name"]
            args = tuple(item["args"])
            cau_enc.setdefault(name, []).append(args)

        for item in raw.get("suppressed", []):
            name = item["name"]
            args = tuple(item["args"])
            sup_enc.setdefault(name, []).append(args)

        cau_flag = bool(cau_enc)
        sup_flag = bool(sup_enc)

        return cau_flag, sup_flag, cau_enc, sup_enc

    # ── Bookkeeping-only path ─────────────────────────────────────────────────

    def log_only(self, events: List[Event]) -> None:
        """
        Write events to the PDP log WITHOUT running EnfGuard.

        Used for pure bookkeeping events (e.g. UnsafeResponse) where no
        enforcement verdict is expected — only the trace record matters for
        future evaluations.

        This corresponds to the real library's log_event() call for non-
        suppressible events.
        """
        for event in events:
            self.schema.validate(event)

        timestep = events[0].args[0] if events and events[0].args else 0
        self.pdp.log_events(events, timestep)


# ── @Instrument class decorator ───────────────────────────────────────────────

class Instrument:
    """
    Class decorator that transparently instruments application classes.

    Usage:

        logger = Logger(pep=my_pep, schema=my_schema, pdp=my_pdp)

        @Instrument(logger)
        class LLMProxy:
            def chat(self, event_id: int, llm_response: str) -> str:
                return llm_response   ← pure application logic

    At decoration time, @Instrument(logger) iterates over the class's methods.
    For each method whose (ClassName, methodName) is registered in pep.mapping,
    it replaces the method with a wrapper that:

        1.  Calls the mapping function with the method's arguments → List[Event]
        2.  Sends those events to logger.log() → verdict
        3.  Calls the original method to get the unmodified result
        4.  Routes the verdict to the registered handler (η_e)
        5.  Returns the enforced result

    The application class body is completely clean — zero enforcement code.
    """

    def __init__(self, logger: Logger) -> None:
        self._logger = logger

    def __call__(self, cls: Type) -> Type:
        """
        Apply instrumentation to the class.

        Iterates over all attributes. For each (ClassName, methodName) pair
        found in the PEP's mapping, replaces the method with a generated
        enforcement wrapper.
        """
        class_name = cls.__qualname__
        logger     = self._logger
        pep        = logger.pep

        for method_name in list(vars(cls)):               # only own methods
            key = (class_name, method_name)
            if key not in pep:
                continue

            original_method = getattr(cls, method_name)
            mapping_fn      = pep[key]                    # η_i: args → events

            # Build wrapper in a closure to capture the correct method/mapping
            wrapped = _make_wrapper(original_method, mapping_fn, logger, pep)
            setattr(cls, method_name, wrapped)

        return cls


def _make_wrapper(
    original_method: Callable,
    mapping_fn:      Callable,
    logger:          "Logger",
    pep:             PEP,
) -> Callable:
    """
    Build the enforcement wrapper for a single instrumented method.

    Separated into its own function (not a nested closure) to avoid the
    classic Python late-binding closure bug when iterating with a for loop.

    Wrapper execution order
    -----------------------
        1.  η_i  : mapping_fn(*args) → List[Event]
        2.  PDP  : logger.log(events) → (cau_flag, sup_flag, cau_enc, sup_enc)
        3.  SuE  : original_method(inst, *args) → original_result (baseline)
        4.  η_e  : handler(event_id, original_result) → enforced_result
        5.  return enforced_result  (or original_result if no verdict)

    Why call the original method even when there is a verdict?
        In the test2 architecture, the original method just returns
        llm_response unchanged — it's cheap. Calling it first produces the
        value that handlers may need (e.g. to prepend a disclaimer to it).
        In a suppression scenario with a costly original method you would
        guard with `if not sup_flag` before calling — omitted here for clarity.
    """
    def wrapper(inst: Any, *args: Any, **kwargs: Any) -> Optional[str]:
        # ── Step 1: η_i — produce events from this method call's arguments ──
        events: List[Event] = mapping_fn(*args, **kwargs)

        # ── Step 2: send to EnfGuard via Logger ──────────────────────────────
        cau_flag, sup_flag, cau_enc, sup_enc = logger.log(events)

        # ── Step 3: call original method to get baseline result ──────────────
        original_result: Any = original_method(inst, *args, **kwargs)

        # ── Step 4a: causation verdict ────────────────────────────────────────
        # When multiple policies fire simultaneously (e.g. Policy 1 causes
        # Disclaimer while Policy 2 causes Block), the handler with the
        # highest priority wins. Priority is determined by registration order
        # in the PEP's causation_handlers dict: first registered = highest.
        # This is why proxy_instrlib_v2.py registers Block before Disclaimer.
        if cau_flag:
            for event_name, handler in pep.cau_event_map.items():
                if event_name in cau_enc:
                    event_id = cau_enc[event_name][0][0]
                    return handler(event_id, original_result)

        # ── Step 4b: suppression verdict ──────────────────────────────────────
        # Not used in test2 architecture (no suppressible events) but kept for
        # completeness and backwards compatibility.
        if sup_flag:
            for event_name, args_list in sup_enc.items():
                handler = pep.sup_event_map.get(event_name)
                if handler is not None:
                    event_id = args_list[0][0]
                    return handler(event_id, original_result)

        # ── Step 5: no enforcement — pass through unchanged ───────────────────
        return original_result

    return wrapper
